// This file was automatically generated by:
//  /playpen/software/SlicerExecutionModel/GenerateCLP/bin/GenerateCLP --InputXML /playpen/Project/airwayAtlas/Pediatric_Airway_Atlas_Code/code/crossSections/computeAreaAndContourWithMeanNorm.xml --OutputCxx /playpen/Project/airwayAtlas/Pediatric_Airway_Atlas_Code/code/crossSections/computeAreaAndContourWithMeanNormCLP.h
//
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <string>
#include <vector>
#include <map>

#include <itksys/ios/sstream>

#include "tclap/CmdLine.h"
#include "ModuleProcessInformation.h"

#ifdef WIN32
#define Module_EXPORT __declspec(dllexport)
#else
#define Module_EXPORT 
#endif

#if defined(main) && !defined(REGISTER_TEST)
// If main defined as a preprocessor symbol, redefine it to the expected entry point.
#undef main
#define main ModuleEntryPoint

extern "C" {
  Module_EXPORT char *GetXMLModuleDescription();
  Module_EXPORT int ModuleEntryPoint(int, char*[]);
}
#endif

extern "C" {
Module_EXPORT char XMLModuleDescription[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"<executable>\n"
"\n"
"    <category>AreaAndContourOfAirway</category>\n"
"    <title>Cross-sectional area and contour of airway</title>\n"
"    <description>Compute the cross-sectional area andcontour of airway.</description>\n"
"    <version>1.0</version>\n"
"    <documentation-url></documentation-url>\n"
"    <license></license>\n"
"    <contributor>Yi Hong</contributor>\n"
"    <acknowledgements></acknowledgements>\n"
"\n"
"    <parameters>\n"
"        <label>Input/Output</label>\n"
"        <description>Input/Output Parameters</description>\n"
"\n"
"        <image>\n"
"            <name>inputModelVTK</name>\n"
"            <label>Input VTK Model</label>\n"
"	    <channel>input</channel>\n"
"	    <index>0</index>\n"
"            <default>None</default>\n"
"            <description>The model of airway.</description>\n"
"        </image>\n"
"        \n"
"       <image>\n"
"            <name>inputMeanNorm</name>\n"
"            <label>Input Mean And Norm</label>\n"
"	    <channel>input</channel>\n"
"	    <index>1</index>\n"
"            <default>None</default>\n"
"            <description>The mean and norm of airway cross-sectional surface.</description>\n"
"        </image>\n"
"\n"
"        <image>\n"
"            <name>inputMouthPosition</name>\n"
"            <label>Input Mouth's Position</label>\n"
"            <channel>input</channel>\n"
"            <index>2</index>\n"
"            <default>None</default>\n"
"            <description>The file with the mouth's position.</description>\n"
"        </image>\n"
"\n"
" 		<image>\n"
"            <name>outputArea</name>\n"
"            <label>Output area file</label>\n"
"            <channel>output</channel>\n"
"            <index>3</index>\n"
"            <default>None</default>\n"
"            <description>Output cross-sectional area.</description>\n"
"        </image>\n"
"\n"
" 		<image>\n"
"            <name>outputPerimeter</name>\n"
"            <label>Output perimeter file</label>\n"
"            <channel>output</channel>\n"
"            <index>4</index>\n"
"            <default>None</default>\n"
"            <description>Output the perimeter of the cross section.</description>\n"
"        </image>\n"
"        \n"
"        <image>\n"
"            <name>outputContourPrefix</name>\n"
"            <label>Output Contour Prefix</label>\n"
"            <channel>output</channel>\n"
"            <index>5</index>\n"
"            <default>None</default>\n"
"            <description>Output cross-sectional contour, create a series of .txt file.</description>\n"
"        </image>\n"
"\n"
"     </parameters>\n"
"\n"
"</executable>\n"
"\n"
"\n"
;

}

void
splitString (const std::string &text,
             const std::string &separators,
             std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  std::string::size_type start = text.find_first_not_of(separators);
  while (start < n)
    {
    std::string::size_type stop = text.find_first_of(separators, start);
    if (stop > n) stop = n;
    words.push_back(text.substr(start, stop - start));
    start = text.find_first_not_of(separators, stop+1);
    }
}

void
splitFilenames (const std::string &text,
                std::vector<std::string> &words)
{
  const std::string::size_type n = text.length();
  bool quoted;
  std::string comma(",");
  std::string quote("\"");
  std::string::size_type start = text.find_first_not_of(comma);
  while (start < n)
    {
    quoted = false;
    std::string::size_type startq = text.find_first_of(quote, start);
    std::string::size_type stopq = text.find_first_of(quote, startq+1);
    std::string::size_type stop = text.find_first_of(comma, start);
    if (stop > n) stop = n;
    if (startq != std::string::npos && stopq != std::string::npos)
      {
      while (startq < stop && stop < stopq && stop != n)
         {
         quoted = true;
         stop = text.find_first_of(comma, stop+1);
         if (stop > n) stop = n;
         }
      }
    if (!quoted)
      {
      words.push_back(text.substr(start, stop - start));
      }
    else
      {
      words.push_back(text.substr(start+1, stop - start-2));
      }
    start = text.find_first_not_of(comma, stop+1);
    }
}

char *GetXMLModuleDescription()
{
   return XMLModuleDescription;
}

#define GENERATE_LOGO
#define GENERATE_XML \
  if (argc >= 2 && (strcmp(argv[1],"--xml") == 0)) \
    { \
    std::cout << GetXMLModuleDescription(); \
    return EXIT_SUCCESS; \
    }
#define GENERATE_TCLAP \
    std::string inputModelVTK = "None"; \
    std::string inputMeanNorm = "None"; \
    std::string inputMouthPosition = "None"; \
    std::string outputArea = "None"; \
    std::string outputPerimeter = "None"; \
    std::string outputContourPrefix = "None"; \
    bool echoSwitch = false; \
    bool xmlSwitch = false; \
    std::string processInformationAddressString = "0"; \
    std::string returnParameterFile; \
    std::string fullDescription("Description: "); \
    fullDescription += "Compute the cross-sectional area andcontour of airway."; \
    if (!std::string("Yi Hong").empty()) \
      { \
      fullDescription += "\nAuthor(s): Yi Hong"; \
      } \
    if (!std::string("").empty()) \
      { \
      fullDescription += "\nAcknowledgements: "; \
      } \
    TCLAP::CmdLine commandLine (fullDescription, \
       ' ', \
      "1.0" ); \
 \
      itksys_ios::ostringstream msg; \
    msg.str("");msg << "The model of airway. (default: " << inputModelVTK << ")"; \
    TCLAP::UnlabeledValueArg<std::string> inputModelVTKArg("inputModelVTK", msg.str(), 1, inputModelVTK, "std::string", commandLine); \
 \
    msg.str("");msg << "The mean and norm of airway cross-sectional surface. (default: " << inputMeanNorm << ")"; \
    TCLAP::UnlabeledValueArg<std::string> inputMeanNormArg("inputMeanNorm", msg.str(), 1, inputMeanNorm, "std::string", commandLine); \
 \
    msg.str("");msg << "The file with the mouth's position. (default: " << inputMouthPosition << ")"; \
    TCLAP::UnlabeledValueArg<std::string> inputMouthPositionArg("inputMouthPosition", msg.str(), 1, inputMouthPosition, "std::string", commandLine); \
 \
    msg.str("");msg << "Output cross-sectional area. (default: " << outputArea << ")"; \
    TCLAP::UnlabeledValueArg<std::string> outputAreaArg("outputArea", msg.str(), 1, outputArea, "std::string", commandLine); \
 \
    msg.str("");msg << "Output the perimeter of the cross section. (default: " << outputPerimeter << ")"; \
    TCLAP::UnlabeledValueArg<std::string> outputPerimeterArg("outputPerimeter", msg.str(), 1, outputPerimeter, "std::string", commandLine); \
 \
    msg.str("");msg << "Output cross-sectional contour, create a series of .txt file. (default: " << outputContourPrefix << ")"; \
    TCLAP::UnlabeledValueArg<std::string> outputContourPrefixArg("outputContourPrefix", msg.str(), 1, outputContourPrefix, "std::string", commandLine); \
 \
    msg.str("");msg << "Echo the command line arguments (default: " << echoSwitch << ")"; \
    TCLAP::SwitchArg echoSwitchArg("", "echo", msg.str(), commandLine, echoSwitch); \
 \
    msg.str("");msg << "Produce xml description of command line arguments (default: " << xmlSwitch << ")"; \
    TCLAP::SwitchArg xmlSwitchArg("", "xml", msg.str(), commandLine, xmlSwitch); \
 \
    msg.str("");msg << "Address of a structure to store process information (progress, abort, etc.). (default: " << processInformationAddressString << ")"; \
    TCLAP::ValueArg<std::string > processInformationAddressStringArg("", "processinformationaddress", msg.str(), 0, processInformationAddressString, "std::string", commandLine); \
 \
    msg.str("");msg << "Filename in which to write simple return parameters (int, float, int-vector, etc.) as opposed to bulk return parameters (image, geometry, transform, measurement, table).";    TCLAP::ValueArg<std::string > returnParameterFileArg("", "returnparameterfile", msg.str(), 0, returnParameterFile, "std::string", commandLine); \
 \
try \
  { \
    /* Build a map of flag aliases to the true flag */ \
    std::map<std::string,std::string> flagAliasMap; \
    std::map<std::string,std::string> deprecatedFlagAliasMap; \
    std::map<std::string,std::string> longFlagAliasMap; \
    std::map<std::string,std::string> deprecatedLongFlagAliasMap; \
    /* Remap flag aliases to the true flag */ \
    std::vector<std::string> targs; \
    std::map<std::string,std::string>::iterator ait; \
    std::map<std::string,std::string>::iterator dait; \
    size_t ac; \
    for (ac=0; ac < static_cast<size_t>(argc); ++ac)  \
       {  \
       if (strlen(argv[ac]) == 2 && argv[ac][0]=='-') \
         { \
         /* short flag case */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         ait = flagAliasMap.find(tflag); \
         dait = deprecatedFlagAliasMap.find(tflag); \
         if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
           { \
           if (ait != flagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("-" + (*ait).second); \
             } \
           else if (dait != deprecatedFlagAliasMap.end()) \
             { \
             std::cout << "Flag \"" << argv[ac] << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("-" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]=='-') \
         { \
         /* long flag case */ \
         std::string tflag(argv[ac], 2, strlen(argv[ac])-2); \
         ait = longFlagAliasMap.find(tflag); \
         dait = deprecatedLongFlagAliasMap.find(tflag); \
         if (ait != longFlagAliasMap.end() || dait != deprecatedLongFlagAliasMap.end()) \
           { \
           if (ait != longFlagAliasMap.end()) \
             { \
             /* remap the flag */ \
             targs.push_back("--" + (*ait).second); \
             } \
           else if (dait != deprecatedLongFlagAliasMap.end()) \
             { \
             std::cout << "Long flag \"" << argv[ac] << "\" is deprecated. Please use long flag \"--" << (*dait).second << "\" instead. " << std::endl; \
             /* remap the flag */ \
             targs.push_back("--" + (*dait).second); \
             } \
           } \
         else \
           { \
           targs.push_back(argv[ac]); \
           } \
         } \
       else if (strlen(argv[ac]) > 2 && argv[ac][0]=='-' && argv[ac][1]!='-') \
         { \
         /* short flag case where multiple flags are given at once ala */ \
         /* "ls -ltr" */ \
         std::string tflag(argv[ac], 1, strlen(argv[ac])-1); \
         std::string rflag("-"); \
         for (std::string::size_type fi=0; fi < tflag.size(); ++fi) \
           { \
           std::string tf(tflag, fi, 1); \
           ait = flagAliasMap.find(tf); \
           dait = deprecatedFlagAliasMap.find(tf); \
           if (ait != flagAliasMap.end() || dait != deprecatedFlagAliasMap.end()) \
             { \
             if (ait != flagAliasMap.end()) \
               { \
               /* remap the flag */ \
               rflag += (*ait).second; \
               } \
             else if (dait != deprecatedFlagAliasMap.end()) \
               { \
               std::cout << "Flag \"-" << tf << "\" is deprecated. Please use flag \"-" << (*dait).second << "\" instead. " << std::endl; \
               /* remap the flag */ \
               rflag += (*dait).second; \
               } \
             } \
           else \
             { \
             rflag += tf; \
             } \
           } \
         targs.push_back(rflag); \
         } \
       else \
         { \
         /* skip the argument without remapping (this is the case for any */ \
         /* arguments for flags */ \
         targs.push_back(argv[ac]); \
         } \
       } \
 \
   /* Remap args to a structure that CmdLine::parse() can understand*/ \
   std::vector<char*> vargs; \
   for (ac = 0; ac < targs.size(); ++ac) \
     {  \
     vargs.push_back(const_cast<char *>(targs[ac].c_str())); \
     } \
    commandLine.parse ( vargs.size(), (char**) &(vargs[0]) ); \
    inputModelVTK = inputModelVTKArg.getValue(); \
    inputMeanNorm = inputMeanNormArg.getValue(); \
    inputMouthPosition = inputMouthPositionArg.getValue(); \
    outputArea = outputAreaArg.getValue(); \
    outputPerimeter = outputPerimeterArg.getValue(); \
    outputContourPrefix = outputContourPrefixArg.getValue(); \
    echoSwitch = echoSwitchArg.getValue(); \
    xmlSwitch = xmlSwitchArg.getValue(); \
    processInformationAddressString = processInformationAddressStringArg.getValue(); \
    returnParameterFile = returnParameterFileArg.getValue(); \
  } \
catch ( TCLAP::ArgException e ) \
  { \
  std::cerr << "error: " << e.error() << " for arg " << e.argId() << std::endl; \
  return ( EXIT_FAILURE ); \
  }
#define GENERATE_ECHOARGS \
if (echoSwitch) \
{ \
std::cout << "Command Line Arguments" << std::endl; \
std::cout << "    inputModelVTK: " << inputModelVTK << std::endl; \
std::cout << "    inputMeanNorm: " << inputMeanNorm << std::endl; \
std::cout << "    inputMouthPosition: " << inputMouthPosition << std::endl; \
std::cout << "    outputArea: " << outputArea << std::endl; \
std::cout << "    outputPerimeter: " << outputPerimeter << std::endl; \
std::cout << "    outputContourPrefix: " << outputContourPrefix << std::endl; \
std::cout << "    echoSwitch: " << echoSwitch << std::endl; \
std::cout << "    xmlSwitch: " << xmlSwitch << std::endl; \
std::cout << "    processInformationAddressString: " << processInformationAddressString << std::endl; \
std::cout << "    returnParameterFile: " << returnParameterFile << std::endl; \
}
#define GENERATE_ProcessInformationAddressDecoding \
ModuleProcessInformation *CLPProcessInformation = 0; \
if (processInformationAddressString != "") \
{ \
sscanf(processInformationAddressString.c_str(), "%p", &CLPProcessInformation); \
}
#define PARSE_ARGS GENERATE_LOGO;GENERATE_XML;GENERATE_TCLAP;GENERATE_ECHOARGS;GENERATE_ProcessInformationAddressDecoding;
